dataset_info:
    dataset_name: 'Matthijs/snacks' #'lewtun/dog_food' 
    image_column_name: 'image'
    label_column_name: 'label'
    #image_size: 224
    #batch_size: 32
model_config:
    checkpoint: 'google/vit-base-patch16-224-in21k' #'microsoft/resnet-50'
training_config:
    output_dir: "./results/"
    #learning_rate: 5.0e-5
    #num_train_epochs: 3.0
    evaluation_strategy: "epoch"
    logging_strategy: "epoch"
    save_strategy: "epoch"
    save_total_limit: 1
    per_device_train_batch_size: 32 # batch_size
    per_device_eval_batch_size: 32 # batch_size